# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"*\n\x12\x43\x61lculationRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\"\n\x10\x43\x61lculationReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xad\x02\n\nCalculator\x12\x43\n\x03\x41\x64\x64\x12\x1e.calculator.CalculationRequest\x1a\x1c.calculator.CalculationReply\x12H\n\x08Subtract\x12\x1e.calculator.CalculationRequest\x1a\x1c.calculator.CalculationReply\x12H\n\x08Multiply\x12\x1e.calculator.CalculationRequest\x1a\x1c.calculator.CalculationReply\x12\x46\n\x06\x44ivide\x12\x1e.calculator.CalculationRequest\x1a\x1c.calculator.CalculationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATIONREQUEST']._serialized_start=32
  _globals['_CALCULATIONREQUEST']._serialized_end=74
  _globals['_CALCULATIONREPLY']._serialized_start=76
  _globals['_CALCULATIONREPLY']._serialized_end=110
  _globals['_CALCULATOR']._serialized_start=113
  _globals['_CALCULATOR']._serialized_end=414
# @@protoc_insertion_point(module_scope)
